apiVersion: v2
name: lgtm-stack
description: A wrapper chart to deploy Loki, Grafana, Tempo, and Prometheus
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  # L - Logs
  - name: loki
    version: 5.43.3
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: 6.15.5
    repository: https://grafana.github.io/helm-charts

  # G - Visualization
  - name: grafana
    version: 7.3.0
    repository: https://grafana.github.io/helm-charts

  # T - Traces
  - name: tempo
    version: 1.7.1
    repository: https://grafana.github.io/helm-charts

  # M - Metrics (using Prometheus for simplicity)
  - name: prometheus
    version: 25.11.0
    repository: https://prometheus-community.github.io/helm-charts